/*
 * This source file was generated by the Gradle 'init' task
 */
package org.turso_sqlite;

public class App {
  

    public static void main(String[] args) {
        String url = "libsql://test-belalakhter.turso.io";
        String authToken = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MTgwMzIwMDcsImlkIjoiMGE2MTYwZTMtMThiNS00NTllLTg3NTYtNTg5MTYxNWU3ZjA0In0.JbZc8uwQWkCfiGjorGfRi902i3FxoAgSoSA0QFP5rNMAvbhm9cmzE6SclObXok_ylJCeqkUGhySZ97ugQ6B_DQ";
        Client client = Client.builder(url).authToken(authToken).build();
        ResultSet rs = client.execute("SELECT * FROM users");
        System.out.println(rs.columns);
        for (ResultSet.Row row : rs.rows) {
            System.out.println(row.toString());
        }
    }
}
